salt-master:
    base-roles:
        - master
    minion-keys-dir: /etc/salt/pki/master/minions
    data-dir: /opt/salt/

salt-minion:
    base-roles:
        - minion
    keys-dir: /etc/salt/pki/minion

bootstrap:
    os-detectors:
        - uname:
            # key => string to find in uname command
            # value => os to tag as (for the operating-systems key below)
            windowsnt: windows
            darwin: osx
            linux: linux
            freebsd: freebsd
    operating-systems:
        linux:
            tmp: /tmp/
            script: 'https://raw.github.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh'
            start-master: service salt-master start
            stop-master: service salt-master stop
            start-minion: service salt-minion start
            stop-minion: service salt-minion stop
        osx:
            tmp: /tmp/
            script: 'bootstrap/scripts/osx.sh'
            start-master: launchctl start org.saltstack.salt-master
            stop-master: launchctl stop org.saltstack.salt-master
            start-minion: launchctl start org.saltstack.salt-minion
            stop-minion: launchctl stop org.saltstack.salt-minion
            files:
                # you must login to http://developer.apple.com and download this file
                - 'osx/xcode462_cltools_10_86938259a.dmg'
                - salt://osx/org.saltstack.salt-master.plist
                - salt://osx/org.saltstack.salt-minion.plist

external-files:
    elasticsearch:
        url: "http://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.20.3.deb"
        path: "configurations/base/states/external_files/elasticsearch/0.20.3.deb"
        sha256: "8f0c113ed904c4338421d87ff3567b8f75bbef9bc0844ee8aa0cec96d1b729fd"
    jenkins-ci.org.key:
        url: "http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key"
        path: "configurations/base/states/external_files/jenkins/jenkins-ci.org.key"
        sha256: "d21585f44b10fefbd677ce0f0d2a1010ad01f0430a0e0a9c032d01e8a05fba41"
    docker:
        url: "http://get.docker.io"
        path: "configurations/base/states/external_files/docker/install.sh"
        sha256: "49f44294c1a87c5d84b271dec543eba5c4f016ecf9f59ccc528babdc88731bd4"

